version: '3.9'
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - /media/mpcrpaul/data/mongo-reddit:/data/db
    ports:
      - 27017:27017
    networks:
       - mongo-network

networks:
  mongo-network: {}