version: "3"
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - /media/mpcrpaul/data/postgres-imtxt:/var/lib/postgresql/data